### PR TITLE
Searching for README pod not only in lib/Module.pm6, but also in lib/…

### PR DESCRIPTION
**Pull request by holli-holzer**
…Module.pod6, docs/Module.pods and README.pod6

### CODE REVIEW

**Comment by kalkin** [comment]
Thank you for your contribution. A few notes:

- Could you please add some tests for this feature?
- You can bump the version to `0.4.2`

Once this is done, I would merge this PR.

Thanks again
kalkin

**Comment by holli-holzer** [comment]
You mean I should expand the extensive test suite you wrote? Seriously the change is trivial but hard to test without writing some extensive framework. I did test it manually though and you can simply proofread the change. Already bumped to 0.4.2, did you even read the diff?

**Comment by holli-holzer** [comment]
oh, you said 0.4.2 not 0.4.1.2, my bad

**Comment by holli-holzer** [comment]
i'll close this one and file a new one with all my changes.

**Pull request closed without merging**
